import { Actionable, Flex, Flexible, Text, Wrap, colors } from "@lenra/app";
const { LenraColors } = colors;

/**
 * Build a list of components from a list of content children generated by @moox/markdown-to-json
 * It converts the html tags to Lenra components
 * @param {ContentChild[]} children 
 * @returns
 */
export function buildContentChildren(children) {
    return children.map(child => {
        if (typeof child === "string") {
            if (child === '\n') return null;
            return Text(child);
        }
        if (!("children" in child)) return null;
        const childrenElements = buildContentChildren(child.children);
        switch (child.tag) {
            case "h1":
                return Text("")
                    .children(childrenElements)
                    .style({
                        fontSize: 24,
                        fontWeight: "bold",
                    });
            case "h2":
                return Text("")
                    .children(childrenElements)
                    .style({
                        fontSize: 20,
                        fontWeight: "bold",
                    });
            case "h3":
                return Text("")
                    .children(childrenElements)
                    .style({
                        fontSize: 18,
                        fontWeight: "bold",
                    });
            case "h4":
                return Text("")
                    .children(childrenElements)
                    .style({
                        fontSize: 16,
                        fontWeight: "bold",
                    });
            case "p":
            case "span":
                return Text("")
                    .children(childrenElements);
            case "strong":
                return Text("")
                    .children(childrenElements)
                    .style({
                        fontWeight: "bold",
                    });
            case "em":
                return Text("")
                    .children(childrenElements)
                    .style({
                        fontStyle: "italic",
                    });
            case "code":
                return Text("")
                    .children(childrenElements)
                    .style({
                        fontFamily: "monospace",
                        // TODO: not managed yet
                        // backgroundColor: Colors.black,
                        // color: Colors.white,
                    });
            case "ul":
                return Flex(childrenElements)
                    .direction("vertical")
                    .padding({ left: 8 });
            case "li":
                return Flex([
                    Text("•"),
                    Flexible(
                        childrenElements.length == 1
                            ? childrenElements[0]
                            : Wrap(childrenElements)
                    )
                ])
                    .spacing(8);
            case "a":
                if (childrenElements.length === 0) return null;
                return Actionable(
                    Text("")
                        .children(childrenElements)
                        .style({
                            color: LenraColors.bluePulse,
                            decoration: "underline"
                        })
                )
                    .onPressed("@lenra:navTo", { path: child.props.href });
            default:
                console.warn("Unknown tag", child.tag);
                return Wrap(childrenElements);
        }
    })
        .filter(child => child !== null);
}